create table "public"."Participation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "event_id" bigint not null
);


alter table "public"."Participation" enable row level security;

CREATE UNIQUE INDEX "Participation_pkey" ON public."Participation" USING btree (id);

alter table "public"."Participation" add constraint "Participation_pkey" PRIMARY KEY using index "Participation_pkey";

alter table "public"."Participation" add constraint "Participation_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Participation" validate constraint "Participation_event_id_fkey";

alter table "public"."Participation" add constraint "Participation_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Participation" validate constraint "Participation_user_id_fkey";

grant delete on table "public"."Participation" to "anon";

grant insert on table "public"."Participation" to "anon";

grant references on table "public"."Participation" to "anon";

grant select on table "public"."Participation" to "anon";

grant trigger on table "public"."Participation" to "anon";

grant truncate on table "public"."Participation" to "anon";

grant update on table "public"."Participation" to "anon";

grant delete on table "public"."Participation" to "authenticated";

grant insert on table "public"."Participation" to "authenticated";

grant references on table "public"."Participation" to "authenticated";

grant select on table "public"."Participation" to "authenticated";

grant trigger on table "public"."Participation" to "authenticated";

grant truncate on table "public"."Participation" to "authenticated";

grant update on table "public"."Participation" to "authenticated";

grant delete on table "public"."Participation" to "service_role";

grant insert on table "public"."Participation" to "service_role";

grant references on table "public"."Participation" to "service_role";

grant select on table "public"."Participation" to "service_role";

grant trigger on table "public"."Participation" to "service_role";

grant truncate on table "public"."Participation" to "service_role";

grant update on table "public"."Participation" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."Participation"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."Participation"
as permissive
for select
to public
using (true);



